---
- hosts: web
  remote_user: ubuntu
  become: yes   # to run the tasks as root
  vars_prompt:
     - name: password
       prompt: "Enter the password"
       private: yes # to hide the password
  roles:
    - web















